### ISSUE TITLE
Create new Visual Studio project file

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/NetFixServer#1]
The existing project file is from Visual Studio 6, which is way too old to be useful these days. An updated Visual Studio 2017 project file would be more usable. In particular, it would help with Continuous Integration tools, such as AppVeyor.

I don't believe any special project settings were used. It's probably easier to create a new blank or console project and re-add the files than to try and upgrade the old project.

@Brett208, can I ask your help with this?

**Comment by Brett208** [comment]
I'll attempt to update to VS2017 in the near future. Perhaps this weekend?

It may be worth considering combining NetFixServer and NetFixClient into a single Git Repository since they are sister projects.

-Brett

**Comment by DanRStevens** [comment]
I'd thought about combining them, but I think separating them makes more sense. There isn't actually any code shared between the two of them. At least not beyond some minor copy/paste similarity. Plus it's unlikely that will change. The server is cross platform. The client isn't, and never will be.

Though you may be getting at the underlying concern where they are both dependent on having a matching protocol. I suppose I'll need to give paired versioning some thought.

I wouldn't worry about a new project file for the client yet. The client is dependent on another project that needs to be revisited.

**Comment by Brett208** [comment]
I've been working on this. I have it compiling in x86 DEBUG mode on VS2017. It throws linker errors in RELEASE mode. A couple of general notes:

 - In ErrorLog.h, the if win32 section was causing an error. I just deleted it and used the iostream header in the if clause and things worked. I also moved the include of the namespace std to ErrorLog.cpp.

 - Do we want to set a specific base address for this to load at? I currently have it set to randomized which I'm thinking is the wrong answer to ensure we do not step on the location reserved for scenarios to load into.

 - If receiving a Warning	C4244 '=': conversion from 'time_t' to 'unsigned int', possible loss of data OPUNetGameServer c:\ . . . \netfixserver\gameserver.cpp 378. Not sure of the fix there, although it may not actually need fixed?

The RELEASE mode specific error are:


Error	LNK2019	unresolved external symbol __imp__bind@12 referenced in function "private: int __thiscall GameServer::AllocSocket(unsigned int &,unsigned short)" (?AllocSocket@GameServer@@AAEHAAIG@Z)	OPUNetGameServer	C:\ . . . \NetFixServer\GameServer.obj	1	

Error	LNK2019	unresolved external symbol __imp__closesocket@4 referenced in function "public: __thiscall GameServer::~GameServer(void)" (??1GameServer@@QAE@XZ)	OPUNetGameServer	C:\Users\Brett\Documents\OutpostUniverseGitHub\NetFixServer\GameServer.obj	1	

Error	LNK2019	unresolved external symbol __imp__ioctlsocket@12 referenced in function "private: int __thiscall GameServer::AllocSocket(unsigned int &,unsigned short)" (?AllocSocket@GameServer@@AAEHAAIG@Z)	OPUNetGameServer	C:\ . . . \NetFixServer\GameServer.obj	1	

Error	LNK2019	unresolved external symbol __imp__htons@4 referenced in function "private: int __thiscall GameServer::AllocSocket(unsigned int &,unsigned short)" (?AllocSocket@GameServer@@AAEHAAIG@Z)	OPUNetGameServer	C:\ . . . \NetFixServer\GameServer.obj	1	

Error	LNK2019	unresolved external symbol __imp__recvfrom@24 referenced in function "public: void __thiscall GameServer::Pump(void)" (?Pump@GameServer@@QAEXXZ)	OPUNetGameServer	C:\ . . . \NetFixServer\GameServer.obj	1	

Error	LNK2019	unresolved external symbol __imp__select@20 referenced in function "public: void __thiscall GameServer::WaitForEvent(void)" (?WaitForEvent@GameServer@@QAEXXZ)	OPUNetGameServer	C:\ . . . \NetFixServer\GameServer.obj	1	

Error	LNK2019	unresolved external symbol __imp__sendto@24 referenced in function "private: void __thiscall GameServer::SendGameInfoRequest(struct sockaddr_in &,unsigned int)" (?SendGameInfoRequest@GameServer@@AAEXAAUsockaddr_in@@I@Z)	OPUNetGameServer	C:\ . . . \NetFixServer\GameServer.obj	1	

Error	LNK2019	unresolved external symbol __imp__socket@12 referenced in function "private: int __thiscall GameServer::AllocSocket(unsigned int &,unsigned short)" (?AllocSocket@GameServer@@AAEHAAIG@Z)	OPUNetGameServer	C:\ . . . \NetFixServer\GameServer.obj	1	

Error	LNK2019	unresolved external symbol __imp__WSAStartup@8 referenced in function "private: int __thiscall GameServer::InitWinsock(void)" (?InitWinsock@GameServer@@AAEHXZ)	OPUNetGameServer	C:\ . . . \NetFixServer\GameServer.obj	1	

Error	LNK2019	unresolved external symbol __imp__WSACleanup@0 referenced in function "public: __thiscall GameServer::~GameServer(void)" (??1GameServer@@QAE@XZ)	OPUNetGameServer	C:\ . . . \NetFixServer\GameServer.obj	1	

I'm going to take a break on this for now.

-Brett

**Comment by DanRStevens** [comment]
Randomized address please. It's a security feature, and this is a network server. Plus, it runs independently from Outpost 2, so there is no need to worry about level DLL load addresses.

No need to fix the errors. Once a project file exists, I can use the AppVeyor CI tool to see and diagnose Windows errors.

There is no doubt going to be some bit rot from changing C++ standards. I'll try to fix those issues later.

Thanks for the error list. I'd like to see if AppVeyor produces the same.

**Comment by DanRStevens** [comment]
Looks like "Ws2_32.lib" needs to be added to the additional dependencies list for the linker input within the project settings. Alternatively this can be handled by adding a source line:
```
#pragma comment(lib, "Ws2_32.lib")
```

I think I would prefer the project settings change rather than the source line.

@Brett208, If you add this project setting, can you please do it as a separate commit, possibly even a separate push. I would like to be able to trigger AppVeyor with and without this setting change. Thanks.

**Comment by Brett208** [comment]
Okay. Thanks for tracking down the missing lib. Turns out it was present in the DEBUG configuration only and not the RELEASE configuration, which is why it would compile in DEBUG mode only. 

There will be 2 commits, each as a separate pull request.

Keep in mind that it will only fail a RELEASE build and not a DEBUG build. I'm assuming that appveyor will build in RELEASE mode, but not sure. It might be helpful to build the code in both configurations in the long term, but that might be getting too complicated with less returns.

-Brett

**Comment by DanRStevens** [comment]
Ahh, that's all to easy to do with Visual Studio. I was constantly making edits to a single project setting when I should have been changing all configurations.

You bring up a good point about the configuration. AppVeyor by default was only set to test the default configuration. For this project, that was Debug.

I added both Debug and Release to the build matrix. As expected, after the initial project commit, the build passed for Debug, and failed for Release. After the fix, the build passes for both Debug and Release.

Looks like this issue is resolved now. There is a project file, which enables building on AppVeyor.
