### ISSUE TITLE
Update Non-Windows Automated Builds

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/NetFixServer#17]
@DanRStevens, It looks like this project could support Linux Builds. Were you interested in adding a clang and gcc automated build?

**Comment by Brett208** [comment]
Looks like Linux builds already existed. I must have just missed it before. Closing the issue.

**Comment by DanRStevens** [comment]
This may be a valid issue. There's only a GCC build on CircleCI. The TravisCI builds are ancient.

We should add a Clang build on CircleCI and retire the TravisCI builds.

**Comment by Brett208** [comment]
OK, reopened to track removal of Travis CI and adding Clang build
