### ISSUE TITLE
Switch GameInfo* to a C++11 container

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/NetFixServer#40]
I would like to switch GameInfo from an array pointer to a C++11 style container. I think a vector might be the best choice. 

This will involve large code changes in GameServer. There is a lot of boilerplate code for memory management and expansion of the GameInfo array that can be removed. Also some tracking variables of the current and max size of the array will no longer be required. 

This is a semi-blocking issue for resolving #32.

**Comment by DanRStevens** [comment]
Sounds like a good plan. That old junk code really needs to go.
