### ISSUE TITLE
Fold GameServer::StartServer into constructor

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/NetFixServer#42]
Folding StartServer's functionality into the constructor will simplify how the class is created and tested since it will no longer be possible to call StartServer function multiple times.

**Comment by Brett208** [comment]
We can no longer return an error code from StartServer if its funcationality is moved into the constructor. Would it be fine to use exceptions instead of error codes? 

I wasn't sure if we were trying to avoid exceptions.

**Comment by DanRStevens** [comment]
Exceptions would be preferred over error codes.
